name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "* * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - name: üìó Classic template
        uses: legoandmars/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'legoandmars/legoandmars' }}
          use_prebuilt_image: master # ‚ö†Ô∏è DO NOT USE THIS OPTION, this is for pulling pre-built master image to make workflow faster 

      - name: üíâ Nightscout Plugin
        uses: legoandmars/metrics@master
        with:
          filename: metrics.plugin.nightscout.svg
          plugin_nightscout: yes
          plugin_nightscout_url: ${{ secrets.NIGHTSCOUT_URL }} # Use the github actions "NIGHTSCOUT_URL" secret as your nightscout site
          plugin_nightscout_datapoints: 12                     # Use the latest 12 blood sugar datapoints to create a graph
          plugins_errors_fatal: ${{ github.repository == 'legoandmars/legoandmars' }}
